name: ai-system
region: nyc1
services:
- name: ai-system
  source_dir: /
  git:
    repo_clone_url: https://github.com/yourusername/ai-communication.git
    branch: main
  dockerfile_path: Dockerfile
  http_port: 3000
  instance_count: 1
  instance_size_slug: professional-xs
  envs:
  - key: NODE_ENV
    value: production
  - key: OPENAI_API_KEY
    type: SECRET
    value: "${OPENAI_API_KEY}"
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 60
  routes:
  - path: /api

- name: ai-monitor
  source_dir: /
  git:
    repo_clone_url: https://github.com/yourusername/ai-communication.git
    branch: main
  dockerfile_path: Dockerfile.monitor
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: NODE_ENV
    value: production
  - key: MONITOR_PORT
    value: "8080"
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 60
  routes:
  - path: /
