name: ai-system-v3
region: nyc1
services:
- name: ai-system
  source_dir: /
  git:
    repo_clone_url: https://github.com/codenlighten/docker-ai-controlled.git
    branch: main
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-xs
  envs:
  - key: NODE_ENV
    value: production
  - key: OPENAI_API_KEY
    type: SECRET
    value: "${OPENAI_API_KEY}"
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 60
  routes:
  - path: /

- name: ai-monitor
  source_dir: /monitor
  git:
    repo_clone_url: https://github.com/codenlighten/docker-ai-controlled.git
    branch: main
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: NODE_ENV
    value: production
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 60
  routes:
  - path: /monitor
