version: '3.8'

services:
  ai-system:
    build: .
    container_name: ai-system
    volumes:
      - ./logs:/var/log/ai-system
      - ./.env:/opt/ai-system/.env
    environment:
      - NODE_ENV=production
      - MONITOR_PORT=3000
    privileged: true
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - ai-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: ai-system-monitor
    volumes:
      - ./monitor:/opt/ai-system/monitor
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONITOR_PORT=8080
    depends_on:
      - ai-system
    networks:
      - ai-net

networks:
  ai-net:
    driver: bridge
